name: Compile Document
on: [push, workflow_dispatch]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Typst
        uses: typst-community/setup-typst@v3
        with:
          cache-dependency-path: template.typ
          
      - name: Compile typst document
        run: typst compile resume.typ resume.pdf
        
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDFs
          path: resume.pdf

      - name: Get current date
        id: date
        run: echo "DATE=$(date +%Y-%m-%d-%H:%M)" >> $GITHUB_ENV

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: "${{ github.ref_name }} — ${{ env.DATE }}"
          files: "*.pdf"
